### ISSUE TITLE
typos in detailed grammar

### ISSUE THREAD

**Issue by rnd0101** [orcmid/miser#15]
Here list-form can't be standalone (eg `[a]` ). Summary grammar seems ok. Remove `<obap-form>` before `<list-form>` ?

https://github.com/orcmid/miser/blob/0a57c7defaa6a4b8291301e52a41ab5ad879a974/oMiser/ob-exp.txt#L111

In other words, `[x,y,z]` or `[]` does not parse, while `x[x,y,z]` does. Just removing `<obap-form>` does not help, so summary grammar may be not ok after all... please, check.

(Adding obap_form to unary seems to work.)

Also `-form-form` in one place, in interpretation.

**Comment by orcmid** [comment]
Good catch.  Here's where standalone list-form belongs:

```
    〈obap-form〉 ::= ( 〈ob-exp〉 ) | 〈list-form〉
                        | 〈obap-form〉 〈list-form〉 
                        | 〈obap-form〉 ( 〈arguments〉 )
```

I added the necessary 

```
    I〈obap-form〉⎾ 〈list-form〉 ⏋=: I〈list-form〉 
```

You're right that there is still no standalone `〈list-form〉`.  It's the standalone 1〈obap-form〉` case that's missing.  So, in the summary grammar and the full grammar

```
    〈ae〉 ::= 〈ae-form〉 | 〈obap-form〉 | 〈obap-form〉 〈ae-form〉
```

along with

```
    I〈ae〉⎾ 〈obap-form〉 ⏋ =: I〈obap-form〉
```

I've made these repairs in ob-exp.txt 0.0.6
