### ISSUE TITLE
What's the REPL/Ob input/output notation?

### ISSUE THREAD

**Issue by orcmid** [orcmid/miser#3]
Here breaking down topics raised in #1 for separate threads.

> @rnd0101: I want to see ... if I can make REPL from Coq representation.

## The Miser REPL Idea ##
The basic idea for a REPL is to have a written (i.e., text) form for reading obs as expressions, *exp*.  So the R-Read part is to accept the text and, if well-formed, obtain the ob that is described as *exp*.  The E-Eval part is to then to perform obap.eval(*exp*).  The P-Print part is to then present that result in the same text form used for input.   This particular Read-Eval-Print-Loop notion stems back to the original implementation of LISP.

A common idea is to present the result in a form that, if itself read (via R-Read), the E-eval would produced the same result.  There are other ways for the result to be retained, and the REPL may need command variations.  That is, the REPL can accept statements, not just expressions for obs, and have more flexibility.  That is all for oFrugal to handle, since, in the Miser project, it is oFrugal that provides a human interface for exercising oMiser operation.

**Key Point 1** In the oFrugal formulation of a REPL, what is read is a *formula* for an *ob*.  The Reader evaluates that formula to construct a representation of the ob that is expressed.  That ob is then taken as the *exp* submitted to `obap.eval()`.  From this perspective, it is appropriate for the default P-Print to produce the result in the R-read notation that could be read back in as the same ob produced from obap.eval(exp), such that it has no further eval.  

**Key Point 2** In the oFrugal notation, the :: and  ‵ operators instruct the construction of the ob being read.  In this notation, ( ... ) is for grouping, white space is for separation, and the symbols are all for individuals.  By convention, primitive individuals all have names begun by "." and lindies all have names begun with a letter.

In the typography, the ‵-character has Unicode code point U+2035 (reversed prime).  (Ed.Note: The Reader will allow ' (apostrophe) for that, but output is always the reverse prime.  The use of acute accent is denigrated because of the trouble it raises in Markdown notation.)

**Key Point 3** there are "sugared" forms that the reader also accepts as expressions for obs.  These can be chosen as more-expressive of an intended use of an ob for data or for applicative-expression script.  In reading, all of these forms are converted to the equivalent canonical ob and that ob is submitted to obap.eval.  The default output of the result is automatically in canonical form with ( ... ) only as required.  There are some ways that oFrugal might be smarter about this and sugar results also, at least with guidance from the user.

The written text for oFrugal ob expressions is sketched in the file [omiser/ob.txt](https://github.com/orcmid/miser/blob/master/oMiser/ob.txt).     This file may also help in the explanation of the separation of [obtheory](https://github.com/orcmid/miser/blob/master/oMiser/obtheory.txt) from [obaptheory](https://github.com/orcmid/miser/blob/master/oMiser/obaptheory.txt), with the second an application atop the first, with supplemental additions in *Ot*, the theory language.

**Comment by rnd0101** [comment]
FYI, I've produced quick-n-dirty [Python version](https://github.com/rnd0101/miser/blob/master/oMiser/mockups/python/miser.py) (I have not checked it yet though)

**Comment by orcmid** [comment]
>FYI, I've produced quick-n-dirty [Python version](https://github.com/rnd0101/miser/blob/master/oMiser/mockups/python/miser.py) (I have not checked it yet though)

I have remarked on this at Question #6, and we can do more if you enable issues on [your fork](https://github.com/rnd0101/miser).

Thank you for expanding the mockups of oMiser.  This is great as demonstration and for confirmation of understanding how oMiser and oFrugal are being approached.

**Comment by rnd0101** [comment]
But I guess that my understanding is still lacking, but I am determined to have it working so I can evaluate how oMiser can be useful to the Eternal Programming. Even if evaluation will be negative, both projects will hopefully benefit. At least, I get hands-on experience, which will help me form design goals for the Eternal Programming language.

What I am sure of, is that it should be applicative (like LISP, ML), good to be concatenative (like Forth and a bit stretching definition of PL - RDF), definitely based on a "miserly" small foundation, be utterly extendable using only that fixed core. Developer ergonomics is also one of the goals. For example, EP language should be easily embeddable into [Jupyter](http://jupyter.org/), so it can be part of learning management systems, running on the Web, etc, etc.

**Comment by orcmid** [comment]
> What I am sure of, is that it should be applicative (like LISP, ML), good to be concatenative (like Forth and a bit stretching definition of PL - RDF), definitely based on a "miserly" small foundation, be utterly extendable using only that fixed core.

 * oMiser is certainly applicative at its level.  
 * I've forgotten what about Forth that makes it concatenative.   I think for the applicative nature of oMiser, functional composition must be the equivalent.  I hesitate to call it catenative.  Also, because application associates to the right in oMiser, concatenating ‵(*g*) to‵(*f*) :: '(*x*) to form *exp* = ‵(*g*) :: ‵(*f*) :: ‵(*x*) has eval(*exp*) provide essentially *g*( *f*( *x* ) ).
 * I'm uncertain over use of RDF or OWL.  I think that makes me neutral on the matter.   I'm content with the  ‹ob› structure, for now.  Revisiting the use of RDF might be a consideration for the future.

Speaking of other representations,, I do [have in mind](http://miser-theory.info/astraendo/pn/2009/11/friday-miser-note-interchanging-code.asp) an XML schema for the export of obs in signed/hash-tagged (and optionally compressed) XML documents that make for (1) fast loading (working bottom-up like reverse-Polish for obs) and (2) a way to load subtrees that are re-used in different parts of the ob only once.   I think the oFrugal REPL is needed first, though.

**Comment by orcmid** [comment]
There has been more refinement of REPL input for oFrugal in a [comment\(https://github.com/orcmid/miser/issues/7#issuecomment-357454209) at Question #7. 

It time to dig out something like an oFrugal grammar, as requested in Question #8.

**Comment by orcmid** [comment]
> @orcmid The basic idea for a REPL is to have a written (i.e., text) form for reading obs as expressions, *exp*. So the R-Read part is to accept the text and, if well-formed, obtain the ob that is described as exp. The E-Eval part is to then to perform obap.eval(exp). The P-Print part is to then present that result in the same text form used for input. This particular Read-Eval-Print-Loop notion stems back to the original implementation of LISP.

***I must recant this observation.***  It is the case that the REPL will Read, Eval, and Print, but it is not by Read delivering an Ob, *exp*, that is evaluated by obap.eval(*exp*) to produce the ob that is then reported (Print) in text form.  That's a very clumsy way of handling the *ob-exp* form that is read for evaluation to an ob result.

There *is* an Eval stage, but it doesn't work that way.  A REPL need not treat Read and Eval as separate stages.  As @rnd0101 has pointed out, it is valuable that the input be checked as well-formed before Eval occurs, but the semantics don't require it and mock-up REPLs will likely Eval in the course of Read, because it is simpler to get right.

There is now a complete grammar for REPL-input *ob-exp* text and the rules for evaluation of those expressions to arrive at a computer ob are rigorous and straightforward.  The summary version is supplied at Question #8 and Question #14.   

I believe this question can now be closed, since there is a precise definition for the expressions that the oFrugal REPL will evaluate to yield obs.
